import "./globals.css";
import StyledComponentsRegistry from '@/lib/registry'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import { CssBaseline } from '@mui/material';
import theme from '../theme';
import { AuthProvider } from "@/contexts/AuthContexts";
import Header from "@/components/Header1/page";
import MUIHeaderMenu from "@/components/Header/MUIHeaderMenu";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>

          <StyledComponentsRegistry>
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <AuthProvider>
                <div>
                  <Header />
                  <MUIHeaderMenu />
                  {children}
                </div>
              </AuthProvider>
            </ThemeProvider>
          </StyledComponentsRegistry>

        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
